### PR TITLE
add callback support in async api

### PR DESCRIPTION
**Pull request by xermicus**
Addition to #29: Now supports callbacks
Ping #7 and #21

### CODE REVIEW

**Comment by XVilka** [comment]
@kriw @HMPerson1 @chinmaydd can you please check this one?

**Comment by chinmaydd** [comment]
This looks great! @xermicus :smile: 

Can you add a line or two of documentation for the `R2Pipe::threads` function highlighting the async API changes? Specifically that the callback function takes in `thread_id as u16, r2pipe output as String` as arguments (just for bookkeeping)

**Comment by xermicus** [comment]
thanks @chinmaydd ! Sure, actually I was considering to update/extend the whole doc a bit soon (TM). I can include that into this PR as well

**Comment by XVilka** [comment]
@xermicus ping?

**Comment by xermicus** [comment]
pong - tried to add little documentation

**Pull request merged**
